provider: hcloud
major-version: 1
env:
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
makeTemplate: bridged

actions:
  preTest:
    - name: Run provider tests
      run: |
        cd provider && go test -v -json -count=1 -cover -timeout 2h -tags=${{ matrix.language }} -parallel 4 . 2>&1 | tee /tmp/gotest.log | gotestfmt
pulumiConvert: 1
registryDocs: true
plugins:
  - name: std
    version: "1.6.2"

  - name: terraform
    version: "1.0.16"
    kind: converter
