// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetStorageBoxSubaccountPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetStorageBoxSubaccountPlainArgs Empty = new GetStorageBoxSubaccountPlainArgs();

    /**
     * ID of the Storage Box Subaccount.
     * 
     */
    @Import(name="id")
    private @Nullable Integer id;

    /**
     * @return ID of the Storage Box Subaccount.
     * 
     */
    public Optional<Integer> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * ID of the Storage Box.
     * 
     */
    @Import(name="storageBoxId", required=true)
    private Integer storageBoxId;

    /**
     * @return ID of the Storage Box.
     * 
     */
    public Integer storageBoxId() {
        return this.storageBoxId;
    }

    /**
     * Username of the Storage Box Subaccount.
     * 
     */
    @Import(name="username")
    private @Nullable String username;

    /**
     * @return Username of the Storage Box Subaccount.
     * 
     */
    public Optional<String> username() {
        return Optional.ofNullable(this.username);
    }

    /**
     * Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
     * 
     */
    @Import(name="withSelector")
    private @Nullable String withSelector;

    /**
     * @return Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
     * 
     */
    public Optional<String> withSelector() {
        return Optional.ofNullable(this.withSelector);
    }

    private GetStorageBoxSubaccountPlainArgs() {}

    private GetStorageBoxSubaccountPlainArgs(GetStorageBoxSubaccountPlainArgs $) {
        this.id = $.id;
        this.storageBoxId = $.storageBoxId;
        this.username = $.username;
        this.withSelector = $.withSelector;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetStorageBoxSubaccountPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetStorageBoxSubaccountPlainArgs $;

        public Builder() {
            $ = new GetStorageBoxSubaccountPlainArgs();
        }

        public Builder(GetStorageBoxSubaccountPlainArgs defaults) {
            $ = new GetStorageBoxSubaccountPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id ID of the Storage Box Subaccount.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Integer id) {
            $.id = id;
            return this;
        }

        /**
         * @param storageBoxId ID of the Storage Box.
         * 
         * @return builder
         * 
         */
        public Builder storageBoxId(Integer storageBoxId) {
            $.storageBoxId = storageBoxId;
            return this;
        }

        /**
         * @param username Username of the Storage Box Subaccount.
         * 
         * @return builder
         * 
         */
        public Builder username(@Nullable String username) {
            $.username = username;
            return this;
        }

        /**
         * @param withSelector Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
         * 
         * @return builder
         * 
         */
        public Builder withSelector(@Nullable String withSelector) {
            $.withSelector = withSelector;
            return this;
        }

        public GetStorageBoxSubaccountPlainArgs build() {
            if ($.storageBoxId == null) {
                throw new MissingRequiredPropertyException("GetStorageBoxSubaccountPlainArgs", "storageBoxId");
            }
            return $;
        }
    }

}
