// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetZoneRrsetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetZoneRrsetPlainArgs Empty = new GetZoneRrsetPlainArgs();

    /**
     * ID of the Zone RRSet.
     * 
     */
    @Import(name="id")
    private @Nullable String id;

    /**
     * @return ID of the Zone RRSet.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Name of the Zone RRSet.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return Name of the Zone RRSet.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Type of the Zone RRSet.
     * 
     */
    @Import(name="type")
    private @Nullable String type;

    /**
     * @return Type of the Zone RRSet.
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/cloud#label-selector).
     * 
     */
    @Import(name="withSelector")
    private @Nullable String withSelector;

    /**
     * @return Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/cloud#label-selector).
     * 
     */
    public Optional<String> withSelector() {
        return Optional.ofNullable(this.withSelector);
    }

    /**
     * ID or Name of the parent Zone.
     * 
     */
    @Import(name="zone", required=true)
    private String zone;

    /**
     * @return ID or Name of the parent Zone.
     * 
     */
    public String zone() {
        return this.zone;
    }

    private GetZoneRrsetPlainArgs() {}

    private GetZoneRrsetPlainArgs(GetZoneRrsetPlainArgs $) {
        this.id = $.id;
        this.name = $.name;
        this.type = $.type;
        this.withSelector = $.withSelector;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetZoneRrsetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetZoneRrsetPlainArgs $;

        public Builder() {
            $ = new GetZoneRrsetPlainArgs();
        }

        public Builder(GetZoneRrsetPlainArgs defaults) {
            $ = new GetZoneRrsetPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id ID of the Zone RRSet.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        /**
         * @param name Name of the Zone RRSet.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        /**
         * @param type Type of the Zone RRSet.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable String type) {
            $.type = type;
            return this;
        }

        /**
         * @param withSelector Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/cloud#label-selector).
         * 
         * @return builder
         * 
         */
        public Builder withSelector(@Nullable String withSelector) {
            $.withSelector = withSelector;
            return this;
        }

        /**
         * @param zone ID or Name of the parent Zone.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            $.zone = zone;
            return this;
        }

        public GetZoneRrsetPlainArgs build() {
            if ($.zone == null) {
                throw new MissingRequiredPropertyException("GetZoneRrsetPlainArgs", "zone");
            }
            return $;
        }
    }

}
