// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class StorageBoxSubaccountAccessSettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final StorageBoxSubaccountAccessSettingsArgs Empty = new StorageBoxSubaccountAccessSettingsArgs();

    /**
     * Whether access from outside the Hetzner network is allowed.
     * 
     */
    @Import(name="reachableExternally")
    private @Nullable Output<Boolean> reachableExternally;

    /**
     * @return Whether access from outside the Hetzner network is allowed.
     * 
     */
    public Optional<Output<Boolean>> reachableExternally() {
        return Optional.ofNullable(this.reachableExternally);
    }

    /**
     * Whether the Subaccount is read-only.
     * 
     */
    @Import(name="readonly")
    private @Nullable Output<Boolean> readonly;

    /**
     * @return Whether the Subaccount is read-only.
     * 
     */
    public Optional<Output<Boolean>> readonly() {
        return Optional.ofNullable(this.readonly);
    }

    /**
     * Whether the Samba subsystem is enabled.
     * 
     */
    @Import(name="sambaEnabled")
    private @Nullable Output<Boolean> sambaEnabled;

    /**
     * @return Whether the Samba subsystem is enabled.
     * 
     */
    public Optional<Output<Boolean>> sambaEnabled() {
        return Optional.ofNullable(this.sambaEnabled);
    }

    /**
     * Whether the SSH subsystem is enabled.
     * 
     */
    @Import(name="sshEnabled")
    private @Nullable Output<Boolean> sshEnabled;

    /**
     * @return Whether the SSH subsystem is enabled.
     * 
     */
    public Optional<Output<Boolean>> sshEnabled() {
        return Optional.ofNullable(this.sshEnabled);
    }

    /**
     * Whether the WebDAV subsystem is enabled.
     * 
     */
    @Import(name="webdavEnabled")
    private @Nullable Output<Boolean> webdavEnabled;

    /**
     * @return Whether the WebDAV subsystem is enabled.
     * 
     */
    public Optional<Output<Boolean>> webdavEnabled() {
        return Optional.ofNullable(this.webdavEnabled);
    }

    private StorageBoxSubaccountAccessSettingsArgs() {}

    private StorageBoxSubaccountAccessSettingsArgs(StorageBoxSubaccountAccessSettingsArgs $) {
        this.reachableExternally = $.reachableExternally;
        this.readonly = $.readonly;
        this.sambaEnabled = $.sambaEnabled;
        this.sshEnabled = $.sshEnabled;
        this.webdavEnabled = $.webdavEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(StorageBoxSubaccountAccessSettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private StorageBoxSubaccountAccessSettingsArgs $;

        public Builder() {
            $ = new StorageBoxSubaccountAccessSettingsArgs();
        }

        public Builder(StorageBoxSubaccountAccessSettingsArgs defaults) {
            $ = new StorageBoxSubaccountAccessSettingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param reachableExternally Whether access from outside the Hetzner network is allowed.
         * 
         * @return builder
         * 
         */
        public Builder reachableExternally(@Nullable Output<Boolean> reachableExternally) {
            $.reachableExternally = reachableExternally;
            return this;
        }

        /**
         * @param reachableExternally Whether access from outside the Hetzner network is allowed.
         * 
         * @return builder
         * 
         */
        public Builder reachableExternally(Boolean reachableExternally) {
            return reachableExternally(Output.of(reachableExternally));
        }

        /**
         * @param readonly Whether the Subaccount is read-only.
         * 
         * @return builder
         * 
         */
        public Builder readonly(@Nullable Output<Boolean> readonly) {
            $.readonly = readonly;
            return this;
        }

        /**
         * @param readonly Whether the Subaccount is read-only.
         * 
         * @return builder
         * 
         */
        public Builder readonly(Boolean readonly) {
            return readonly(Output.of(readonly));
        }

        /**
         * @param sambaEnabled Whether the Samba subsystem is enabled.
         * 
         * @return builder
         * 
         */
        public Builder sambaEnabled(@Nullable Output<Boolean> sambaEnabled) {
            $.sambaEnabled = sambaEnabled;
            return this;
        }

        /**
         * @param sambaEnabled Whether the Samba subsystem is enabled.
         * 
         * @return builder
         * 
         */
        public Builder sambaEnabled(Boolean sambaEnabled) {
            return sambaEnabled(Output.of(sambaEnabled));
        }

        /**
         * @param sshEnabled Whether the SSH subsystem is enabled.
         * 
         * @return builder
         * 
         */
        public Builder sshEnabled(@Nullable Output<Boolean> sshEnabled) {
            $.sshEnabled = sshEnabled;
            return this;
        }

        /**
         * @param sshEnabled Whether the SSH subsystem is enabled.
         * 
         * @return builder
         * 
         */
        public Builder sshEnabled(Boolean sshEnabled) {
            return sshEnabled(Output.of(sshEnabled));
        }

        /**
         * @param webdavEnabled Whether the WebDAV subsystem is enabled.
         * 
         * @return builder
         * 
         */
        public Builder webdavEnabled(@Nullable Output<Boolean> webdavEnabled) {
            $.webdavEnabled = webdavEnabled;
            return this;
        }

        /**
         * @param webdavEnabled Whether the WebDAV subsystem is enabled.
         * 
         * @return builder
         * 
         */
        public Builder webdavEnabled(Boolean webdavEnabled) {
            return webdavEnabled(Output.of(webdavEnabled));
        }

        public StorageBoxSubaccountAccessSettingsArgs build() {
            return $;
        }
    }

}
