// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud
{
    public static class GetServerTypes
    {
        /// <summary>
        /// Provides a list of available Hetzner Cloud Server Types.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using HCloud = Pulumi.HCloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var ds = Output.Create(HCloud.GetServerTypes.InvokeAsync());
        ///         var workers = new List&lt;HCloud.Server&gt;();
        ///         for (var rangeIndex = 0; rangeIndex &lt; 3; rangeIndex++)
        ///         {
        ///             var range = new { Value = rangeIndex };
        ///             workers.Add(new HCloud.Server($"workers-{range.Value}", new HCloud.ServerArgs
        ///             {
        ///                 Image = "debian-9",
        ///                 ServerType = ds.Apply(ds =&gt; ds.Names)[range.Value],
        ///             }));
        ///         }
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetServerTypesResult> InvokeAsync(GetServerTypesArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetServerTypesResult>("hcloud:index/getServerTypes:getServerTypes", args ?? new GetServerTypesArgs(), options.WithVersion());
    }


    public sealed class GetServerTypesArgs : Pulumi.InvokeArgs
    {
        [Input("serverTypeIds")]
        private List<string>? _serverTypeIds;
        [Obsolete(@"Use server_types list instead")]
        public List<string> ServerTypeIds
        {
            get => _serverTypeIds ?? (_serverTypeIds = new List<string>());
            set => _serverTypeIds = value;
        }

        public GetServerTypesArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetServerTypesResult
    {
        public readonly ImmutableArray<string> Descriptions;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Names;
        public readonly ImmutableArray<string> ServerTypeIds;
        /// <summary>
        /// (list) List of all server types. See `data.hcloud_type` for schema.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServerTypesServerTypeResult> ServerTypes;

        [OutputConstructor]
        private GetServerTypesResult(
            ImmutableArray<string> descriptions,

            string id,

            ImmutableArray<string> names,

            ImmutableArray<string> serverTypeIds,

            ImmutableArray<Outputs.GetServerTypesServerTypeResult> serverTypes)
        {
            Descriptions = descriptions;
            Id = id;
            Names = names;
            ServerTypeIds = serverTypeIds;
            ServerTypes = serverTypes;
        }
    }
}
