// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud
{
    public static class GetStorageBoxSubaccount
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using HCloud = Pulumi.HCloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var config = new Config();
        ///     var storageBoxId = config.RequireObject&lt;dynamic&gt;("storageBoxId");
        ///     var byId = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         Id = 2,
        ///     });
        /// 
        ///     var byUsername = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         Username = "u507137-sub1",
        ///     });
        /// 
        ///     var byLabelSelector = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         WithSelector = "team=billing",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetStorageBoxSubaccountResult> InvokeAsync(GetStorageBoxSubaccountArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetStorageBoxSubaccountResult>("hcloud:index/getStorageBoxSubaccount:getStorageBoxSubaccount", args ?? new GetStorageBoxSubaccountArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using HCloud = Pulumi.HCloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var config = new Config();
        ///     var storageBoxId = config.RequireObject&lt;dynamic&gt;("storageBoxId");
        ///     var byId = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         Id = 2,
        ///     });
        /// 
        ///     var byUsername = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         Username = "u507137-sub1",
        ///     });
        /// 
        ///     var byLabelSelector = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         WithSelector = "team=billing",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetStorageBoxSubaccountResult> Invoke(GetStorageBoxSubaccountInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetStorageBoxSubaccountResult>("hcloud:index/getStorageBoxSubaccount:getStorageBoxSubaccount", args ?? new GetStorageBoxSubaccountInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using HCloud = Pulumi.HCloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var config = new Config();
        ///     var storageBoxId = config.RequireObject&lt;dynamic&gt;("storageBoxId");
        ///     var byId = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         Id = 2,
        ///     });
        /// 
        ///     var byUsername = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         Username = "u507137-sub1",
        ///     });
        /// 
        ///     var byLabelSelector = HCloud.GetStorageBoxSubaccount.Invoke(new()
        ///     {
        ///         StorageBoxId = storageBoxId,
        ///         WithSelector = "team=billing",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetStorageBoxSubaccountResult> Invoke(GetStorageBoxSubaccountInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetStorageBoxSubaccountResult>("hcloud:index/getStorageBoxSubaccount:getStorageBoxSubaccount", args ?? new GetStorageBoxSubaccountInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetStorageBoxSubaccountArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the Storage Box Subaccount.
        /// </summary>
        [Input("id")]
        public int? Id { get; set; }

        /// <summary>
        /// ID of the Storage Box.
        /// </summary>
        [Input("storageBoxId", required: true)]
        public int StorageBoxId { get; set; }

        /// <summary>
        /// Username of the Storage Box Subaccount.
        /// </summary>
        [Input("username")]
        public string? Username { get; set; }

        /// <summary>
        /// Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
        /// </summary>
        [Input("withSelector")]
        public string? WithSelector { get; set; }

        public GetStorageBoxSubaccountArgs()
        {
        }
        public static new GetStorageBoxSubaccountArgs Empty => new GetStorageBoxSubaccountArgs();
    }

    public sealed class GetStorageBoxSubaccountInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the Storage Box Subaccount.
        /// </summary>
        [Input("id")]
        public Input<int>? Id { get; set; }

        /// <summary>
        /// ID of the Storage Box.
        /// </summary>
        [Input("storageBoxId", required: true)]
        public Input<int> StorageBoxId { get; set; } = null!;

        /// <summary>
        /// Username of the Storage Box Subaccount.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        /// <summary>
        /// Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
        /// </summary>
        [Input("withSelector")]
        public Input<string>? WithSelector { get; set; }

        public GetStorageBoxSubaccountInvokeArgs()
        {
        }
        public static new GetStorageBoxSubaccountInvokeArgs Empty => new GetStorageBoxSubaccountInvokeArgs();
    }


    [OutputType]
    public sealed class GetStorageBoxSubaccountResult
    {
        /// <summary>
        /// Access settings for the Subaccount.
        /// </summary>
        public readonly Outputs.GetStorageBoxSubaccountAccessSettingsResult AccessSettings;
        /// <summary>
        /// Description of the Storage Box Subaccount.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Home directory of the Storage Box Subaccount.
        /// </summary>
        public readonly string HomeDirectory;
        /// <summary>
        /// ID of the Storage Box Subaccount.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// User-defined [labels](https://docs.hetzner.cloud/reference/cloud#labels) (key-value pairs) for the resource.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// FQDN of the Storage Box Subaccount.
        /// </summary>
        public readonly string Server;
        /// <summary>
        /// ID of the Storage Box.
        /// </summary>
        public readonly int StorageBoxId;
        /// <summary>
        /// Username of the Storage Box Subaccount.
        /// </summary>
        public readonly string Username;
        /// <summary>
        /// Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
        /// </summary>
        public readonly string? WithSelector;

        [OutputConstructor]
        private GetStorageBoxSubaccountResult(
            Outputs.GetStorageBoxSubaccountAccessSettingsResult accessSettings,

            string description,

            string homeDirectory,

            int id,

            ImmutableDictionary<string, string> labels,

            string server,

            int storageBoxId,

            string username,

            string? withSelector)
        {
            AccessSettings = accessSettings;
            Description = description;
            HomeDirectory = homeDirectory;
            Id = id;
            Labels = labels;
            Server = server;
            StorageBoxId = storageBoxId;
            Username = username;
            WithSelector = withSelector;
        }
    }
}
