// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud
{
    public static class GetServerType
    {
        /// <summary>
        /// Provides details about a specific Hetzner Cloud Server Type.
        /// Use this resource to get detailed information about specific Server Type.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using HCloud = Pulumi.HCloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var ds1 = Output.Create(HCloud.GetServerType.InvokeAsync(new HCloud.GetServerTypeArgs
        ///         {
        ///             Name = "cx11",
        ///         }));
        ///         var ds2 = Output.Create(HCloud.GetServerType.InvokeAsync(new HCloud.GetServerTypeArgs
        ///         {
        ///             Id = 1,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetServerTypeResult> InvokeAsync(GetServerTypeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetServerTypeResult>("hcloud:index/getServerType:getServerType", args ?? new GetServerTypeArgs(), options.WithDefaults());

        /// <summary>
        /// Provides details about a specific Hetzner Cloud Server Type.
        /// Use this resource to get detailed information about specific Server Type.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using HCloud = Pulumi.HCloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var ds1 = Output.Create(HCloud.GetServerType.InvokeAsync(new HCloud.GetServerTypeArgs
        ///         {
        ///             Name = "cx11",
        ///         }));
        ///         var ds2 = Output.Create(HCloud.GetServerType.InvokeAsync(new HCloud.GetServerTypeArgs
        ///         {
        ///             Id = 1,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetServerTypeResult> Invoke(GetServerTypeInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetServerTypeResult>("hcloud:index/getServerType:getServerType", args ?? new GetServerTypeInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetServerTypeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the server_type.
        /// </summary>
        [Input("id")]
        public int? Id { get; set; }

        /// <summary>
        /// Name of the server_type.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetServerTypeArgs()
        {
        }
    }

    public sealed class GetServerTypeInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the server_type.
        /// </summary>
        [Input("id")]
        public Input<int>? Id { get; set; }

        /// <summary>
        /// Name of the server_type.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetServerTypeInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetServerTypeResult
    {
        /// <summary>
        /// (int) Number of cpu cores a Server of this type will have.
        /// </summary>
        public readonly int Cores;
        public readonly string CpuType;
        /// <summary>
        /// (string) Description of the server_type.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// (int) Disk size a Server of this type will have in GB.
        /// </summary>
        public readonly int Disk;
        /// <summary>
        /// (int) Unique ID of the server_type.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// (int) Memory a Server of this type will have in GB.
        /// </summary>
        public readonly int Memory;
        /// <summary>
        /// (string) Name of the server_type.
        /// </summary>
        public readonly string Name;
        public readonly string StorageType;

        [OutputConstructor]
        private GetServerTypeResult(
            int cores,

            string cpuType,

            string description,

            int disk,

            int id,

            int memory,

            string name,

            string storageType)
        {
            Cores = cores;
            CpuType = cpuType;
            Description = description;
            Disk = disk;
            Id = id;
            Memory = memory;
            Name = name;
            StorageType = storageType;
        }
    }
}
