// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.HCloud
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("hcloud");
        public static string? Endpoint { get; set; } = __config.Get("endpoint");

        /// <summary>
        /// The API token to access the Hetzner cloud.
        /// </summary>
        public static string? Token { get; set; } = __config.Get("token");

    }
}
