# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetStorageBoxTypesResult',
    'AwaitableGetStorageBoxTypesResult',
    'get_storage_box_types',
    'get_storage_box_types_output',
]

@pulumi.output_type
class GetStorageBoxTypesResult:
    """
    A collection of values returned by getStorageBoxTypes.
    """
    def __init__(__self__, id=None, storage_box_types=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if storage_box_types and not isinstance(storage_box_types, list):
            raise TypeError("Expected argument 'storage_box_types' to be a list")
        pulumi.set(__self__, "storage_box_types", storage_box_types)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="storageBoxTypes")
    def storage_box_types(self) -> Sequence['outputs.GetStorageBoxTypesStorageBoxTypeResult']:
        return pulumi.get(self, "storage_box_types")


class AwaitableGetStorageBoxTypesResult(GetStorageBoxTypesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetStorageBoxTypesResult(
            id=self.id,
            storage_box_types=self.storage_box_types)


def get_storage_box_types(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetStorageBoxTypesResult:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_hcloud as hcloud

    all = hcloud.get_storage_box_types()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('hcloud:index/getStorageBoxTypes:getStorageBoxTypes', __args__, opts=opts, typ=GetStorageBoxTypesResult).value

    return AwaitableGetStorageBoxTypesResult(
        id=pulumi.get(__ret__, 'id'),
        storage_box_types=pulumi.get(__ret__, 'storage_box_types'))
def get_storage_box_types_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetStorageBoxTypesResult]:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_hcloud as hcloud

    all = hcloud.get_storage_box_types()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('hcloud:index/getStorageBoxTypes:getStorageBoxTypes', __args__, opts=opts, typ=GetStorageBoxTypesResult)
    return __ret__.apply(lambda __response__: GetStorageBoxTypesResult(
        id=pulumi.get(__response__, 'id'),
        storage_box_types=pulumi.get(__response__, 'storage_box_types')))
