// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud.Outputs
{

    [OutputType]
    public sealed class GetFloatingIpsFloatingIpResult
    {
        public readonly bool DeleteProtection;
        public readonly string Description;
        public readonly string HomeLocation;
        public readonly int Id;
        public readonly string IpAddress;
        public readonly string IpNetwork;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string? Name;
        public readonly int ServerId;
        public readonly string Type;

        [OutputConstructor]
        private GetFloatingIpsFloatingIpResult(
            bool deleteProtection,

            string description,

            string homeLocation,

            int id,

            string ipAddress,

            string ipNetwork,

            ImmutableDictionary<string, string> labels,

            string? name,

            int serverId,

            string type)
        {
            DeleteProtection = deleteProtection;
            Description = description;
            HomeLocation = homeLocation;
            Id = id;
            IpAddress = ipAddress;
            IpNetwork = ipNetwork;
            Labels = labels;
            Name = name;
            ServerId = serverId;
            Type = type;
        }
    }
}
