// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud.Outputs
{

    [OutputType]
    public sealed class GetLoadBalancerServiceHealthCheckResult
    {
        public readonly Outputs.GetLoadBalancerServiceHealthCheckHttpResult Http;
        public readonly int Interval;
        public readonly int Port;
        public readonly string Protocol;
        public readonly int Retries;
        public readonly int Timeout;

        [OutputConstructor]
        private GetLoadBalancerServiceHealthCheckResult(
            Outputs.GetLoadBalancerServiceHealthCheckHttpResult http,

            int interval,

            int port,

            string protocol,

            int retries,

            int timeout)
        {
            Http = http;
            Interval = interval;
            Port = port;
            Protocol = protocol;
            Retries = retries;
            Timeout = timeout;
        }
    }
}
