// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud.Outputs
{

    [OutputType]
    public sealed class GetServerTypesServerTypeLocationResult
    {
        /// <summary>
        /// Whether the Server Type is temporarily unavailable in this Location.
        /// </summary>
        public readonly bool Available;
        /// <summary>
        /// Date of the Server Type deprecation announcement.
        /// </summary>
        public readonly string DeprecationAnnounced;
        /// <summary>
        /// ID of the Location.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Whether the Server Type is deprecated.
        /// </summary>
        public readonly bool IsDeprecated;
        /// <summary>
        /// Name of the Location.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Whether the Server Type is recommended in this Location.
        /// </summary>
        public readonly bool Recommended;
        /// <summary>
        /// Date of the Server Type removal. After this date, the Server Type cannot be used anymore.
        /// </summary>
        public readonly string UnavailableAfter;

        [OutputConstructor]
        private GetServerTypesServerTypeLocationResult(
            bool available,

            string deprecationAnnounced,

            int id,

            bool isDeprecated,

            string name,

            bool recommended,

            string unavailableAfter)
        {
            Available = available;
            DeprecationAnnounced = deprecationAnnounced;
            Id = id;
            IsDeprecated = isDeprecated;
            Name = name;
            Recommended = recommended;
            UnavailableAfter = unavailableAfter;
        }
    }
}
