// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud.Outputs
{

    [OutputType]
    public sealed class GetServerTypesServerTypeResult
    {
        public readonly string Architecture;
        public readonly double Cores;
        public readonly string CpuType;
        public readonly string DeprecationAnnounced;
        public readonly string Description;
        public readonly double Disk;
        public readonly int Id;
        public readonly int IncludedTraffic;
        public readonly bool IsDeprecated;
        public readonly double Memory;
        public readonly string Name;
        public readonly string StorageType;
        public readonly string UnavailableAfter;

        [OutputConstructor]
        private GetServerTypesServerTypeResult(
            string architecture,

            double cores,

            string cpuType,

            string deprecationAnnounced,

            string description,

            double disk,

            int id,

            int includedTraffic,

            bool isDeprecated,

            double memory,

            string name,

            string storageType,

            string unavailableAfter)
        {
            Architecture = architecture;
            Cores = cores;
            CpuType = cpuType;
            DeprecationAnnounced = deprecationAnnounced;
            Description = description;
            Disk = disk;
            Id = id;
            IncludedTraffic = includedTraffic;
            IsDeprecated = isDeprecated;
            Memory = memory;
            Name = name;
            StorageType = storageType;
            UnavailableAfter = unavailableAfter;
        }
    }
}
