// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package hcloud

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// Provides details about a specific Hetzner Cloud Datacenter.
// Use this resource to get detailed information about specific datacenter.
func GetDatacenter(ctx *pulumi.Context, args *GetDatacenterArgs, opts ...pulumi.InvokeOption) (*GetDatacenterResult, error) {
	var rv GetDatacenterResult
	err := ctx.Invoke("hcloud:index/getDatacenter:getDatacenter", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDatacenter.
type GetDatacenterArgs struct {
	Id   *int    `pulumi:"id"`
	Name *string `pulumi:"name"`
}

// A collection of values returned by getDatacenter.
type GetDatacenterResult struct {
	AvailableServerTypeIds []int                  `pulumi:"availableServerTypeIds"`
	Description            string                 `pulumi:"description"`
	Id                     int                    `pulumi:"id"`
	Location               map[string]interface{} `pulumi:"location"`
	Name                   string                 `pulumi:"name"`
	SupportedServerTypeIds []int                  `pulumi:"supportedServerTypeIds"`
}
