// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hcloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-hcloud/sdk/go/hcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a list of Hetzner Storage Images.
//
// It is recommended to always provide the image architecture (using ”with_architecture”).
//
// See the [Image API documentation](https://docs.hetzner.cloud/reference/cloud#images) for more details.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-hcloud/sdk/go/hcloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := hcloud.GetImages(ctx, &hcloud.GetImagesArgs{
//				WithArchitectures: []string{
//					"x86",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = hcloud.GetImages(ctx, &hcloud.GetImagesArgs{
//				WithSelector: pulumi.StringRef("key=value"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetImages(ctx *pulumi.Context, args *GetImagesArgs, opts ...pulumi.InvokeOption) (*GetImagesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetImagesResult
	err := ctx.Invoke("hcloud:index/getImages:getImages", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImages.
type GetImagesArgs struct {
	// Include deprecated images.
	IncludeDeprecated *bool `pulumi:"includeDeprecated"`
	// Sort results by created date.
	MostRecent *bool `pulumi:"mostRecent"`
	// Filter results by architecture, for example `x86` or `arm`.
	WithArchitectures []string `pulumi:"withArchitectures"`
	// Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
	WithSelector *string `pulumi:"withSelector"`
	// Filter results by statuses, for example `creating` or `available`.
	WithStatuses []string `pulumi:"withStatuses"`
}

// A collection of values returned by getImages.
type GetImagesResult struct {
	// The ID of this resource.
	Id     string           `pulumi:"id"`
	Images []GetImagesImage `pulumi:"images"`
	// Include deprecated images.
	IncludeDeprecated *bool `pulumi:"includeDeprecated"`
	// Sort results by created date.
	MostRecent *bool `pulumi:"mostRecent"`
	// Filter results by architecture, for example `x86` or `arm`.
	WithArchitectures []string `pulumi:"withArchitectures"`
	// Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
	WithSelector *string `pulumi:"withSelector"`
	// Filter results by statuses, for example `creating` or `available`.
	WithStatuses []string `pulumi:"withStatuses"`
}

func GetImagesOutput(ctx *pulumi.Context, args GetImagesOutputArgs, opts ...pulumi.InvokeOption) GetImagesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetImagesResultOutput, error) {
			args := v.(GetImagesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("hcloud:index/getImages:getImages", args, GetImagesResultOutput{}, options).(GetImagesResultOutput), nil
		}).(GetImagesResultOutput)
}

// A collection of arguments for invoking getImages.
type GetImagesOutputArgs struct {
	// Include deprecated images.
	IncludeDeprecated pulumi.BoolPtrInput `pulumi:"includeDeprecated"`
	// Sort results by created date.
	MostRecent pulumi.BoolPtrInput `pulumi:"mostRecent"`
	// Filter results by architecture, for example `x86` or `arm`.
	WithArchitectures pulumi.StringArrayInput `pulumi:"withArchitectures"`
	// Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
	WithSelector pulumi.StringPtrInput `pulumi:"withSelector"`
	// Filter results by statuses, for example `creating` or `available`.
	WithStatuses pulumi.StringArrayInput `pulumi:"withStatuses"`
}

func (GetImagesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetImagesArgs)(nil)).Elem()
}

// A collection of values returned by getImages.
type GetImagesResultOutput struct{ *pulumi.OutputState }

func (GetImagesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetImagesResult)(nil)).Elem()
}

func (o GetImagesResultOutput) ToGetImagesResultOutput() GetImagesResultOutput {
	return o
}

func (o GetImagesResultOutput) ToGetImagesResultOutputWithContext(ctx context.Context) GetImagesResultOutput {
	return o
}

// The ID of this resource.
func (o GetImagesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetImagesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetImagesResultOutput) Images() GetImagesImageArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []GetImagesImage { return v.Images }).(GetImagesImageArrayOutput)
}

// Include deprecated images.
func (o GetImagesResultOutput) IncludeDeprecated() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetImagesResult) *bool { return v.IncludeDeprecated }).(pulumi.BoolPtrOutput)
}

// Sort results by created date.
func (o GetImagesResultOutput) MostRecent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetImagesResult) *bool { return v.MostRecent }).(pulumi.BoolPtrOutput)
}

// Filter results by architecture, for example `x86` or `arm`.
func (o GetImagesResultOutput) WithArchitectures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []string { return v.WithArchitectures }).(pulumi.StringArrayOutput)
}

// Filter results using a [Label Selector](https://docs.hetzner.cloud/reference/hetzner#label-selector).
func (o GetImagesResultOutput) WithSelector() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetImagesResult) *string { return v.WithSelector }).(pulumi.StringPtrOutput)
}

// Filter results by statuses, for example `creating` or `available`.
func (o GetImagesResultOutput) WithStatuses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []string { return v.WithStatuses }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetImagesResultOutput{})
}
