// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hcloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-hcloud/sdk/go/hcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides details about multiple Hetzner Cloud Placement Groups.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-hcloud/sdk/go/hcloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := hcloud.GetPlacementGroups(ctx, &hcloud.GetPlacementGroupsArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = hcloud.GetPlacementGroups(ctx, &hcloud.GetPlacementGroupsArgs{
//				WithSelector: pulumi.StringRef("key=value"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetPlacementGroups(ctx *pulumi.Context, args *GetPlacementGroupsArgs, opts ...pulumi.InvokeOption) (*GetPlacementGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPlacementGroupsResult
	err := ctx.Invoke("hcloud:index/getPlacementGroups:getPlacementGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPlacementGroups.
type GetPlacementGroupsArgs struct {
	// Sorts list by date.
	MostRecent *bool `pulumi:"mostRecent"`
	// [Label selector](https://docs.hetzner.cloud/#overview-label-selector)
	WithSelector *string `pulumi:"withSelector"`
}

// A collection of values returned by getPlacementGroups.
type GetPlacementGroupsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id         string `pulumi:"id"`
	MostRecent *bool  `pulumi:"mostRecent"`
	// (list) List of all matching placement groups. See `data.hcloud_placement_group` for schema.
	PlacementGroups []GetPlacementGroupsPlacementGroup `pulumi:"placementGroups"`
	WithSelector    *string                            `pulumi:"withSelector"`
}

func GetPlacementGroupsOutput(ctx *pulumi.Context, args GetPlacementGroupsOutputArgs, opts ...pulumi.InvokeOption) GetPlacementGroupsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetPlacementGroupsResultOutput, error) {
			args := v.(GetPlacementGroupsArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv GetPlacementGroupsResult
			secret, err := ctx.InvokePackageRaw("hcloud:index/getPlacementGroups:getPlacementGroups", args, &rv, "", opts...)
			if err != nil {
				return GetPlacementGroupsResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(GetPlacementGroupsResultOutput)
			if secret {
				return pulumi.ToSecret(output).(GetPlacementGroupsResultOutput), nil
			}
			return output, nil
		}).(GetPlacementGroupsResultOutput)
}

// A collection of arguments for invoking getPlacementGroups.
type GetPlacementGroupsOutputArgs struct {
	// Sorts list by date.
	MostRecent pulumi.BoolPtrInput `pulumi:"mostRecent"`
	// [Label selector](https://docs.hetzner.cloud/#overview-label-selector)
	WithSelector pulumi.StringPtrInput `pulumi:"withSelector"`
}

func (GetPlacementGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPlacementGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getPlacementGroups.
type GetPlacementGroupsResultOutput struct{ *pulumi.OutputState }

func (GetPlacementGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPlacementGroupsResult)(nil)).Elem()
}

func (o GetPlacementGroupsResultOutput) ToGetPlacementGroupsResultOutput() GetPlacementGroupsResultOutput {
	return o
}

func (o GetPlacementGroupsResultOutput) ToGetPlacementGroupsResultOutputWithContext(ctx context.Context) GetPlacementGroupsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetPlacementGroupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPlacementGroupsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPlacementGroupsResultOutput) MostRecent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetPlacementGroupsResult) *bool { return v.MostRecent }).(pulumi.BoolPtrOutput)
}

// (list) List of all matching placement groups. See `data.hcloud_placement_group` for schema.
func (o GetPlacementGroupsResultOutput) PlacementGroups() GetPlacementGroupsPlacementGroupArrayOutput {
	return o.ApplyT(func(v GetPlacementGroupsResult) []GetPlacementGroupsPlacementGroup { return v.PlacementGroups }).(GetPlacementGroupsPlacementGroupArrayOutput)
}

func (o GetPlacementGroupsResultOutput) WithSelector() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlacementGroupsResult) *string { return v.WithSelector }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPlacementGroupsResultOutput{})
}
