// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package hcloud

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupServer(ctx *pulumi.Context, args *LookupServerArgs, opts ...pulumi.InvokeOption) (*LookupServerResult, error) {
	var rv LookupServerResult
	err := ctx.Invoke("hcloud:index/getServer:getServer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServer.
type LookupServerArgs struct {
	Id   *int    `pulumi:"id"`
	Name *string `pulumi:"name"`
	// Deprecated: Please use the with_selector property instead.
	Selector     *string  `pulumi:"selector"`
	WithSelector *string  `pulumi:"withSelector"`
	WithStatuses []string `pulumi:"withStatuses"`
}

// A collection of values returned by getServer.
type LookupServerResult struct {
	BackupWindow string                 `pulumi:"backupWindow"`
	Backups      bool                   `pulumi:"backups"`
	Datacenter   string                 `pulumi:"datacenter"`
	Id           int                    `pulumi:"id"`
	Image        string                 `pulumi:"image"`
	Ipv4Address  string                 `pulumi:"ipv4Address"`
	Ipv6Address  string                 `pulumi:"ipv6Address"`
	Ipv6Network  string                 `pulumi:"ipv6Network"`
	Iso          string                 `pulumi:"iso"`
	Labels       map[string]interface{} `pulumi:"labels"`
	Location     string                 `pulumi:"location"`
	Name         string                 `pulumi:"name"`
	Rescue       string                 `pulumi:"rescue"`
	// Deprecated: Please use the with_selector property instead.
	Selector     *string  `pulumi:"selector"`
	ServerType   string   `pulumi:"serverType"`
	Status       string   `pulumi:"status"`
	WithSelector *string  `pulumi:"withSelector"`
	WithStatuses []string `pulumi:"withStatuses"`
}
