// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetLoadBalancerAlgorithm {
    /**
     * @return (string) Type of the target. `server` or `label_selector`
     * 
     */
    private String type;

    private GetLoadBalancerAlgorithm() {}
    /**
     * @return (string) Type of the target. `server` or `label_selector`
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLoadBalancerAlgorithm defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String type;
        public Builder() {}
        public Builder(GetLoadBalancerAlgorithm defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public GetLoadBalancerAlgorithm build() {
            final var _resultValue = new GetLoadBalancerAlgorithm();
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
