// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetLocationsLocation {
    /**
     * @return Name of the closest city to the Location. City name and optionally state in short form.
     * 
     */
    private String city;
    /**
     * @return Country the Location resides in. ISO 3166-1 alpha-2 code of the country.
     * 
     */
    private String country;
    /**
     * @return Description of the Location.
     * 
     */
    private String description;
    /**
     * @return ID of the Location.
     * 
     */
    private Integer id;
    /**
     * @return Latitude of the city closest to the Location.
     * 
     */
    private Double latitude;
    /**
     * @return Longitude of the city closest to the Location.
     * 
     */
    private Double longitude;
    /**
     * @return Name of the Location.
     * 
     */
    private String name;
    /**
     * @return Name of the Network Zone this Location resides in.
     * 
     */
    private String networkZone;

    private GetLocationsLocation() {}
    /**
     * @return Name of the closest city to the Location. City name and optionally state in short form.
     * 
     */
    public String city() {
        return this.city;
    }
    /**
     * @return Country the Location resides in. ISO 3166-1 alpha-2 code of the country.
     * 
     */
    public String country() {
        return this.country;
    }
    /**
     * @return Description of the Location.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return ID of the Location.
     * 
     */
    public Integer id() {
        return this.id;
    }
    /**
     * @return Latitude of the city closest to the Location.
     * 
     */
    public Double latitude() {
        return this.latitude;
    }
    /**
     * @return Longitude of the city closest to the Location.
     * 
     */
    public Double longitude() {
        return this.longitude;
    }
    /**
     * @return Name of the Location.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Name of the Network Zone this Location resides in.
     * 
     */
    public String networkZone() {
        return this.networkZone;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLocationsLocation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String city;
        private String country;
        private String description;
        private Integer id;
        private Double latitude;
        private Double longitude;
        private String name;
        private String networkZone;
        public Builder() {}
        public Builder(GetLocationsLocation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.city = defaults.city;
    	      this.country = defaults.country;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.latitude = defaults.latitude;
    	      this.longitude = defaults.longitude;
    	      this.name = defaults.name;
    	      this.networkZone = defaults.networkZone;
        }

        @CustomType.Setter
        public Builder city(String city) {
            if (city == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "city");
            }
            this.city = city;
            return this;
        }
        @CustomType.Setter
        public Builder country(String country) {
            if (country == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "country");
            }
            this.country = country;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(Integer id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder latitude(Double latitude) {
            if (latitude == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "latitude");
            }
            this.latitude = latitude;
            return this;
        }
        @CustomType.Setter
        public Builder longitude(Double longitude) {
            if (longitude == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "longitude");
            }
            this.longitude = longitude;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder networkZone(String networkZone) {
            if (networkZone == null) {
              throw new MissingRequiredPropertyException("GetLocationsLocation", "networkZone");
            }
            this.networkZone = networkZone;
            return this;
        }
        public GetLocationsLocation build() {
            final var _resultValue = new GetLocationsLocation();
            _resultValue.city = city;
            _resultValue.country = country;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.latitude = latitude;
            _resultValue.longitude = longitude;
            _resultValue.name = name;
            _resultValue.networkZone = networkZone;
            return _resultValue;
        }
    }
}
