// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class GetStorageBoxSnapshotPlan {
    /**
     * @return Day of the month when the Snapshot Plan is executed. Null means every day.
     * 
     */
    private Integer dayOfMonth;
    /**
     * @return Day of the week when the Snapshot Plan is executed. Starts at 0 for Sunday til 6 for Saturday. Note that this differs from the API, which uses 1 (Monday) through 7 (Sunday). Null means every day.
     * 
     */
    private Integer dayOfWeek;
    /**
     * @return Hour when the Snapshot Plan is executed (UTC).
     * 
     */
    private Integer hour;
    /**
     * @return Maximum amount of Snapshots that will be created by this Snapshot Plan. Older Snapshots will be deleted.
     * 
     */
    private Integer maxSnapshots;
    /**
     * @return Minute when the Snapshot Plan is executed (UTC).
     * 
     */
    private Integer minute;

    private GetStorageBoxSnapshotPlan() {}
    /**
     * @return Day of the month when the Snapshot Plan is executed. Null means every day.
     * 
     */
    public Integer dayOfMonth() {
        return this.dayOfMonth;
    }
    /**
     * @return Day of the week when the Snapshot Plan is executed. Starts at 0 for Sunday til 6 for Saturday. Note that this differs from the API, which uses 1 (Monday) through 7 (Sunday). Null means every day.
     * 
     */
    public Integer dayOfWeek() {
        return this.dayOfWeek;
    }
    /**
     * @return Hour when the Snapshot Plan is executed (UTC).
     * 
     */
    public Integer hour() {
        return this.hour;
    }
    /**
     * @return Maximum amount of Snapshots that will be created by this Snapshot Plan. Older Snapshots will be deleted.
     * 
     */
    public Integer maxSnapshots() {
        return this.maxSnapshots;
    }
    /**
     * @return Minute when the Snapshot Plan is executed (UTC).
     * 
     */
    public Integer minute() {
        return this.minute;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetStorageBoxSnapshotPlan defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer dayOfMonth;
        private Integer dayOfWeek;
        private Integer hour;
        private Integer maxSnapshots;
        private Integer minute;
        public Builder() {}
        public Builder(GetStorageBoxSnapshotPlan defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dayOfMonth = defaults.dayOfMonth;
    	      this.dayOfWeek = defaults.dayOfWeek;
    	      this.hour = defaults.hour;
    	      this.maxSnapshots = defaults.maxSnapshots;
    	      this.minute = defaults.minute;
        }

        @CustomType.Setter
        public Builder dayOfMonth(Integer dayOfMonth) {
            if (dayOfMonth == null) {
              throw new MissingRequiredPropertyException("GetStorageBoxSnapshotPlan", "dayOfMonth");
            }
            this.dayOfMonth = dayOfMonth;
            return this;
        }
        @CustomType.Setter
        public Builder dayOfWeek(Integer dayOfWeek) {
            if (dayOfWeek == null) {
              throw new MissingRequiredPropertyException("GetStorageBoxSnapshotPlan", "dayOfWeek");
            }
            this.dayOfWeek = dayOfWeek;
            return this;
        }
        @CustomType.Setter
        public Builder hour(Integer hour) {
            if (hour == null) {
              throw new MissingRequiredPropertyException("GetStorageBoxSnapshotPlan", "hour");
            }
            this.hour = hour;
            return this;
        }
        @CustomType.Setter
        public Builder maxSnapshots(Integer maxSnapshots) {
            if (maxSnapshots == null) {
              throw new MissingRequiredPropertyException("GetStorageBoxSnapshotPlan", "maxSnapshots");
            }
            this.maxSnapshots = maxSnapshots;
            return this;
        }
        @CustomType.Setter
        public Builder minute(Integer minute) {
            if (minute == null) {
              throw new MissingRequiredPropertyException("GetStorageBoxSnapshotPlan", "minute");
            }
            this.minute = minute;
            return this;
        }
        public GetStorageBoxSnapshotPlan build() {
            final var _resultValue = new GetStorageBoxSnapshotPlan();
            _resultValue.dayOfMonth = dayOfMonth;
            _resultValue.dayOfWeek = dayOfWeek;
            _resultValue.hour = hour;
            _resultValue.maxSnapshots = maxSnapshots;
            _resultValue.minute = minute;
            return _resultValue;
        }
    }
}
