// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.HCloud.Inputs
{

    public sealed class GetFirewallApplyToArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// (string) Label Selector to select servers the firewall is applied to. Empty if a server is directly
        /// referenced
        /// </summary>
        [Input("labelSelector", required: true)]
        public string LabelSelector { get; set; } = null!;

        /// <summary>
        /// (int) ID of a server where the firewall is applied to. `0` if applied to a label_selector
        /// </summary>
        [Input("server", required: true)]
        public int Server { get; set; }

        public GetFirewallApplyToArgs()
        {
        }
        public static new GetFirewallApplyToArgs Empty => new GetFirewallApplyToArgs();
    }
}
