// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getPlacementGroup(args?: GetPlacementGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetPlacementGroupResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("hcloud:index/getPlacementGroup:getPlacementGroup", {
        "id": args.id,
        "labels": args.labels,
        "mostRecent": args.mostRecent,
        "name": args.name,
        "type": args.type,
        "withSelector": args.withSelector,
    }, opts);
}

/**
 * A collection of arguments for invoking getPlacementGroup.
 */
export interface GetPlacementGroupArgs {
    readonly id?: number;
    readonly labels?: {[key: string]: any};
    readonly mostRecent?: boolean;
    readonly name?: string;
    readonly type?: string;
    readonly withSelector?: string;
}

/**
 * A collection of values returned by getPlacementGroup.
 */
export interface GetPlacementGroupResult {
    readonly id?: number;
    readonly labels?: {[key: string]: any};
    readonly mostRecent?: boolean;
    readonly name: string;
    readonly servers: number[];
    readonly type?: string;
    readonly withSelector?: string;
}
