// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a Hetzner Cloud Load Balancer to represent a Load Balancer in the Hetzner Cloud.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as hcloud from "@pulumi/hcloud";
 *
 * const myServer = new hcloud.Server("my_server", {
 *     name: "server-%d",
 *     serverType: "cx11",
 *     image: "ubuntu-18.04",
 * });
 * const loadBalancer = new hcloud.LoadBalancer("load_balancer", {
 *     name: "my-load-balancer",
 *     loadBalancerType: "lb11",
 *     location: "nbg1",
 * });
 * const loadBalancerTarget = new hcloud.LoadBalancerTarget("load_balancer_target", {
 *     type: "server",
 *     loadBalancerId: loadBalancer.id,
 *     serverId: myServer.id,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 *
 * ## Import
 *
 * Load Balancers can be imported using its `id`:
 *
 * ```sh
 * $ pulumi import hcloud:index/loadBalancer:LoadBalancer my_load_balancer id
 * ```
 */
export class LoadBalancer extends pulumi.CustomResource {
    /**
     * Get an existing LoadBalancer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LoadBalancerState, opts?: pulumi.CustomResourceOptions): LoadBalancer {
        return new LoadBalancer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'hcloud:index/loadBalancer:LoadBalancer';

    /**
     * Returns true if the given object is an instance of LoadBalancer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LoadBalancer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LoadBalancer.__pulumiType;
    }

    /**
     * Configuration of the algorithm the Load Balancer use.
     */
    public readonly algorithm!: pulumi.Output<outputs.LoadBalancerAlgorithm>;
    /**
     * Enable or disable delete protection. See "Delete Protection" in the Provider Docs for details.
     */
    public readonly deleteProtection!: pulumi.Output<boolean | undefined>;
    /**
     * (string) IPv4 Address of the Load Balancer.
     */
    public /*out*/ readonly ipv4!: pulumi.Output<string>;
    /**
     * (string) IPv6 Address of the Load Balancer.
     */
    public /*out*/ readonly ipv6!: pulumi.Output<string>;
    /**
     * User-defined labels (key-value pairs) should be created with.
     */
    public readonly labels!: pulumi.Output<{[key: string]: any}>;
    /**
     * Type of the Load Balancer.
     */
    public readonly loadBalancerType!: pulumi.Output<string>;
    /**
     * The location name of the Load Balancer. Require when no networkZone is set.
     */
    public readonly location!: pulumi.Output<string>;
    /**
     * Name of the Load Balancer.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * (int) ID of the first private network that this Load Balancer is connected to.
     */
    public /*out*/ readonly networkId!: pulumi.Output<number>;
    /**
     * (string) IP of the Load Balancer in the first private network that it is connected to.
     */
    public /*out*/ readonly networkIp!: pulumi.Output<string>;
    /**
     * The Network Zone of the Load Balancer. Require when no location is set.
     */
    public readonly networkZone!: pulumi.Output<string>;
    /**
     * @deprecated Use hcloud.LoadBalancerTarget resource instead. This allows the full control over the selected targets.
     */
    public readonly targets!: pulumi.Output<outputs.LoadBalancerTarget[]>;

    /**
     * Create a LoadBalancer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LoadBalancerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LoadBalancerArgs | LoadBalancerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LoadBalancerState | undefined;
            resourceInputs["algorithm"] = state ? state.algorithm : undefined;
            resourceInputs["deleteProtection"] = state ? state.deleteProtection : undefined;
            resourceInputs["ipv4"] = state ? state.ipv4 : undefined;
            resourceInputs["ipv6"] = state ? state.ipv6 : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["loadBalancerType"] = state ? state.loadBalancerType : undefined;
            resourceInputs["location"] = state ? state.location : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkId"] = state ? state.networkId : undefined;
            resourceInputs["networkIp"] = state ? state.networkIp : undefined;
            resourceInputs["networkZone"] = state ? state.networkZone : undefined;
            resourceInputs["targets"] = state ? state.targets : undefined;
        } else {
            const args = argsOrState as LoadBalancerArgs | undefined;
            if ((!args || args.loadBalancerType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'loadBalancerType'");
            }
            resourceInputs["algorithm"] = args ? args.algorithm : undefined;
            resourceInputs["deleteProtection"] = args ? args.deleteProtection : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["loadBalancerType"] = args ? args.loadBalancerType : undefined;
            resourceInputs["location"] = args ? args.location : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkZone"] = args ? args.networkZone : undefined;
            resourceInputs["targets"] = args ? args.targets : undefined;
            resourceInputs["ipv4"] = undefined /*out*/;
            resourceInputs["ipv6"] = undefined /*out*/;
            resourceInputs["networkId"] = undefined /*out*/;
            resourceInputs["networkIp"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LoadBalancer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LoadBalancer resources.
 */
export interface LoadBalancerState {
    /**
     * Configuration of the algorithm the Load Balancer use.
     */
    algorithm?: pulumi.Input<inputs.LoadBalancerAlgorithm>;
    /**
     * Enable or disable delete protection. See "Delete Protection" in the Provider Docs for details.
     */
    deleteProtection?: pulumi.Input<boolean>;
    /**
     * (string) IPv4 Address of the Load Balancer.
     */
    ipv4?: pulumi.Input<string>;
    /**
     * (string) IPv6 Address of the Load Balancer.
     */
    ipv6?: pulumi.Input<string>;
    /**
     * User-defined labels (key-value pairs) should be created with.
     */
    labels?: pulumi.Input<{[key: string]: any}>;
    /**
     * Type of the Load Balancer.
     */
    loadBalancerType?: pulumi.Input<string>;
    /**
     * The location name of the Load Balancer. Require when no networkZone is set.
     */
    location?: pulumi.Input<string>;
    /**
     * Name of the Load Balancer.
     */
    name?: pulumi.Input<string>;
    /**
     * (int) ID of the first private network that this Load Balancer is connected to.
     */
    networkId?: pulumi.Input<number>;
    /**
     * (string) IP of the Load Balancer in the first private network that it is connected to.
     */
    networkIp?: pulumi.Input<string>;
    /**
     * The Network Zone of the Load Balancer. Require when no location is set.
     */
    networkZone?: pulumi.Input<string>;
    /**
     * @deprecated Use hcloud.LoadBalancerTarget resource instead. This allows the full control over the selected targets.
     */
    targets?: pulumi.Input<pulumi.Input<inputs.LoadBalancerTarget>[]>;
}

/**
 * The set of arguments for constructing a LoadBalancer resource.
 */
export interface LoadBalancerArgs {
    /**
     * Configuration of the algorithm the Load Balancer use.
     */
    algorithm?: pulumi.Input<inputs.LoadBalancerAlgorithm>;
    /**
     * Enable or disable delete protection. See "Delete Protection" in the Provider Docs for details.
     */
    deleteProtection?: pulumi.Input<boolean>;
    /**
     * User-defined labels (key-value pairs) should be created with.
     */
    labels?: pulumi.Input<{[key: string]: any}>;
    /**
     * Type of the Load Balancer.
     */
    loadBalancerType: pulumi.Input<string>;
    /**
     * The location name of the Load Balancer. Require when no networkZone is set.
     */
    location?: pulumi.Input<string>;
    /**
     * Name of the Load Balancer.
     */
    name?: pulumi.Input<string>;
    /**
     * The Network Zone of the Load Balancer. Require when no location is set.
     */
    networkZone?: pulumi.Input<string>;
    /**
     * @deprecated Use hcloud.LoadBalancerTarget resource instead. This allows the full control over the selected targets.
     */
    targets?: pulumi.Input<pulumi.Input<inputs.LoadBalancerTarget>[]>;
}
